include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    unnecessary_to_list_in_spreads: false
    curly_braces_in_flow_control_structures: false
    prefer_single_quotes: true
